image: busybox:latest

stages:
  - build
  - test
  - deploy

build-pr:
  stage: build
  script:
    - mkdir -p public
    - cd public
    - echo test1 >> index.html
    - echo test2 >> about.html
    - mkdir -p temp
    - cd temp
    - echo test1 >> temp1.txt
    - echo test2 >> temp2.txt
  artifacts:
    paths:
      - public/
    exclude:
      - public/temp/**/*

build1:
  stage: build
  script:
    - echo "Do your build here"
    - echo one >> index.html
  artifacts:
    paths:
      - index.html
    expire_in: 30 days

test1:
  stage: test
  script:
    - echo "Do a test here"
    - echo "For example run a test suite"
    - grep one index.html

deploy1:
  stage: deploy
  script:
    - echo "Do your deploy here"
  environment: production

pages:
  stage: deploy
  script:
    - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
